=== Geekly/wp-army/assets/army.xsd
<?xml version="1.0"?>

<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">    
    <xs:element name="armylist">
        <xs:complexType>
            <xs:all> 
                <xs:element name="faction" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="player" type="xs:string"/>        
                <xs:element name="army">
                    <xs:complexType>
                        <xs:all>    
                            <xs:element name="themeforce" type="xs:string"/>
                            <xs:element name="tier" type="xs:string"/>
                            <xs:element name="caster">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="points" type="xs:integer"/>
                                        <xs:element name="focusfury" type="xs:integer"/>                       
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="models">
                                <xs:complexType>
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name="caster" nillable="false">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="points" type="xs:integer"/>
                                                    <xs:element name="focusfury" type="xs:integer"/>                       
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="unit" nillable="true">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="pointcost" type="xs:integer"/>
                                                    <xs:element name="minmax" type="xs:string"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>                               
                                        <xs:element name="solo" maxOccurs="unbounded" nillable="true">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="pointcost" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>    
            </xs:all>
        </xs:complexType>
    </xs:element>
    <!--<xs:element name="Caster" type="ModelUnit"/>
    <xs:element name="models">
        <xs:complexType>
        </xs:complexType>
    </xs:element>-->
    
    <!--<xs:complexType name="ModelUnit">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="PointCost" type="xs:string"/>
            <<xs:element name="ModelType" type="ModelType"/>
            <xs:element name="UnitAttachment" type="UnitAttachment"/>
        </xs:sequence>
    </xs:complexType>
    -->
    
    <!--<xs:complexType name="UnitAttachment"/>
    <xs:sequence>
        <xs:element name="Name" type="xs:string"/>
        <xs:element name="Unit" type="ModelUnit"/>
    </xs:sequence>-->
</xs:schema>

=== Geekly/wp-army/assets/testarmy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<armylist
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='army.xsd'>
    
        <faction>Circle Orboros</faction>
        <description>Army I brought last week</description>
        <player>Geekly</player>
        <army>
            <themeforce>Rock of Orboros</themeforce>
            <tier>4</tier>
            <caster>
                <name>Baldur</name>
                <points>6</points>
                <focusfury>6</focusfury>
            </caster>
            <models>
                <solo>    
                    <name>Warpwolf Stalker</name>
                    <pointcost>10</pointcost>
                </solo>
                <unit>
                    <name>Wold Shrimp</name>
                    <pointcost>5</pointcost>
                    <minmax>max</minmax>  
                </unit>
            </models>
        </army>
</armylist>
